
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbfdntuygzyxldpxdmem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iZmRudHV5Z3p5eGxkcHhkbWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTA2NzgsImV4cCI6MjA2Mjk4NjY3OH0.3-hPPPYE7K-deier_4ikfL1DpfshwHTyA_W1nu41yFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
